#!/bin/bash
cd /tmp || exit
if [ -f tempr-cli ]
then
rm -rf tempr-cli
else
wget -qc "https://raw.githubusercontent.com/sivel/speedtest-cli/master/speedtest.py" -O tempr-cli
chmod +x tempr-cli
./tempr-cli
rm -rf tempr-cli
fi
